### ISSUE TITLE
Compares' to hashcat

### ISSUE THREAD

**Issue by ashraful1978** [D7EAD/HashPlusPlus#11]
Please let me which better in between hashcat or HashPlusPlus..

**Comment by D7EAD** [comment]
Hi.

Hashcat has superior performance to Hash++ due to its included OpenCL and CUDA parallel-processing features which perform massively parallel calculations on the GPU rather than the CPU. Hash++ runs solely on the CPU and, as a result, does not have these parallel capabilities implemented nor do I plan on doing it anytime soon.

If you'd like to benchmark Hashcat on your system, you can run the command <code>hashcat -b</code>. You can also supply a custom device via the <code>-d</code> option.

**Comment by ashraful1978** [comment]
Thanks
