### ISSUE TITLE
'struct std::array<unsigned char, 64 ' has no member named '_Elems'

### ISSUE THREAD

**Issue by adgnaf** [D7EAD/HashPlusPlus#12]
hashpp.h: 547  error: 'struct std::array<unsigned char, 64' has no member named '_Elems'.

**Comment by D7EAD** [comment]
Hi.

This error is caused by a per-platform implementation of the C++ std::array template class where _Elems may be the name of its internal buffer on one system's implementation of the C++ standard library, but another name on another.

This is my fault for using a platform dependent member and I will fix it as soon as possible.

Thanks.

**Comment by D7EAD** [comment]
This should now be fixed. See #13
